services:
  - type: web
    name: resume-genie-backend
    runtime: python
    buildCommand: ""
    startCommand: gunicorn server:app
    envVars:
      - key: FLASK_ENV
        value: production